### ISSUE TITLE
Cannot Clear Text Programatically

### ISSUE THREAD

**Issue by zwilkin** [dotMorten/XamarinFormsControls#18] opened 2018-09-21 14:06 UTC
First off, AMAZING product! Very easy to set up and get right to using.

That being said, I am running into an issue where I cannot clear/remove the text from the field through code - the only way is to manually delete the characters through the keyboard.

I have tried the following
`AutoSuggestBox.Text = string.Empty`
`AutoSuggestBox.Text = ""`
`AutoSuggestBox.SetValue(AutoSuggestBox.TextProperty, string.Empty);`
`AutoSuggestBox.SetValue(AutoSuggestBox.TextProperty, "");`

@dotMorten, is there something that I am not doing right? I do not have any variable bindings.
If not. could you please take a look at what could be causing this issue.

Thanks!
Zach

**Comment by mfeingol** [comment] 2018-11-15 20:13
I'm seeing the same problem. I'll add that binding the value of Text to a property, and then assigning to that property doesn't work either.

Because of this, it is impossible to assign an initial value to the AutoSuggestBox.

**Comment by RaashVision** [comment] 2018-12-18 15:57
I think the solution for this text issue is discussed in issue 'Bound Text property not updating ViewModel MVVM #10' (https://github.com/dotMorten/XamarinFormsControls/issues/10). Currently the text property only support oneway databinding have to change to two way binding.

**Comment by dotMorten** [comment] 2019-01-11 23:05
I tried both updating a view model and directly updating the property, and it worked fine for me on iOS, Android and UWP.

I don't think the TwoWay binding issue is related, as that would only address pushing data back from the control up to the view model, and this issue is the other way around.

Both these things works:
```cs
myAutoSuggestBox.Text = DateTime.Now.Ticks.ToString();
((MyViewModel)BindingContext).Text = DateTime.Now.Ticks.ToString();
```

I'm going to close this as non-repro, but please feel free to submit a reproducer sample, and I'll be happy to re-open.

**Comment by mfeingol** [comment] 2019-01-12 05:18
Please post in this forum when your new version is out, and I'll try to set up a simple repro (or confirm fixed).

**Comment by mfeingol** [comment] 2019-01-23 01:53
Here's a simple repro using your version `0.5.0`. If you set a breakpoint on the `Text` setter in the main page, you'll see that after the page assigns a value to the property, the AutoSuggestBox turns around and sets it to `String.Empty` via the two-way binding.

(Context: my goal is to simply to assign an initial value to the AutoSuggestBox's text.)

[XamarinFormsSample.zip](https://github.com/dotMorten/XamarinFormsControls/files/2785327/XamarinFormsSample.zip)

**Comment by dotMorten** [comment] 2019-01-23 05:54
Aaah I see! Luckily this was fixed with commit https://github.com/dotMorten/XamarinFormsControls/commit/6aae1dafc6fb2564ac15b08fd6e27e9afc4583bf :smile:

**Closed by dotMorten** 2019-01-23 05:54 UTC
Labels: F-AutoSuggestBox
