### ISSUE TITLE
Null Reference Exception raised when navigating back from a page that contains the AutoSuggestBox

### ISSUE THREAD

**Issue by OlteanuRadu** [dotMorten/XamarinFormsControls#28] opened 2019-01-16 16:49 UTC
I have a ContentPage that contains the AutoSuggestBox as following : 
  <dm:AutoSuggestBox x:Name="v"
                        PlaceholderText="Search"              
                        WidthRequest="200"
                        Text="{Binding AddressText, Mode=TwoWay}"
                        temsSource="{Binding Src,Mode=TwoWay}">
                    </dm:AutoSuggestBox>

When I navigate back from this page, I receive the following exception on iOS: 

 at dotMorten.Xamarin.Forms.AutoSuggestBoxRenderer.UpdateTextColor () [0x00000] in E:\GitHub\dotMorten\XamarinFormsControls\AutoSuggestBox\dotMorten.Xamarin.Forms.AutoSuggestBox\AutoSuggestBoxRenderer.cs:170 
  at dotMorten.Xamarin.Forms.AutoSuggestBoxRenderer.OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x000dd] in E:\GitHub\dotMorten\XamarinFormsControls\AutoSuggestBox\dotMorten.Xamarin.Forms.AutoSuggestBox\AutoSuggestBoxRenderer.cs:83 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x0012a] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x0008c] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Platform.iOS.ViewRenderer`2[TView,TNativeView].Dispose (System.Boolean disposing) [0x00000] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/Foundation/NSObject2.cs:147 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0003f] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose () [0x00000] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00058] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/Foundation/NSObject2.cs:147 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0003f] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose () [0x00000] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00058] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/Foundation/NSObject2.cs:147 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0003f] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose () [0x00000] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Platform.iOS.ScrollViewRenderer.Dispose (System.Boolean disposing) [0x00016] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/Foundation/NSObject2.cs:147 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0003f] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose () [0x00000] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00058] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/Foundation/NSObject2.cs:147 
  at Xamarin.Forms.Platform.iOS.DisposeHelpers.DisposeModalAndChildRenderers (Xamarin.Forms.Element view) [0x00038] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Platform.iOS.Platform.HandleChildRemoved (System.Object sender, Xamarin.Forms.ElementEventArgs e) [0x0000a] in <18e93b810a4a4e2f919016f742528d37>:0 
  at Xamarin.Forms.Element.OnDescendantRemoved (Xamarin.Forms.Element child) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:617 
  at Xamarin.Forms.Element.OnDescendantRemoved (Xamarin.Forms.Element child) [0x00018] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:618 
  at Xamarin.Forms.Element.OnChildRemoved (Xamarin.Forms.Element child) [0x0001f] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:357 
  at Xamarin.Forms.VisualElement.OnChildRemoved (Xamarin.Forms.Element child) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:751 
  at Xamarin.Forms.Page.OnInternalRemoved (Xamarin.Forms.VisualElement view) [0x00013] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:380 
  at Xamarin.Forms.Page.InternalChildrenOnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00022] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:358 
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00018] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:263 
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedAction action, System.Object item, System.Int32 index) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:338 
  at System.Collections.ObjectModel.ObservableCollection`1[T].RemoveItem (System.Int32 index) [0x00021] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:182 
  at System.Collections.ObjectModel.Collection`1[T].Remove (T item) [0x00027] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/ObjectModel/Collection.cs:130 
  at Xamarin.Forms.NavigationPage+<Xamarin-Forms-INavigationPageController-RemoveAsyncInner>d__69.MoveNext () [0x000e8] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:304 
--- End of stack trace from previous location where exception was thrown ---
  at Xamarin.Forms.Platform.iOS.NavigationRenderer+<UpdateFormsInnerNavigation>d__75.MoveNext () [0x000a7] in <18e93b810a4a4e2f919016f742528d37>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Xamarin.Forms.Platform.iOS.NavigationRenderer+ParentingViewController+<DidMoveToParentViewController>d__41.MoveNext () [0x0007f] in <18e93b810a4a4e2f919016f742528d37>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1023 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/Foundation/NSAction.cs:178 
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at Substance.iOS.Application.Main (System.String[] args) [0x00001] in /Users/user149779/Substance/Substance/Substance/Substance.iOS/Main.cs:17 

on Android, it's not acting like this, and I'm using the same code base, must be something iOS specific that makes this exception to be thrown.

![image](https://user-images.githubusercontent.com/6471559/51264528-66767d00-19bf-11e9-9a6d-93fcfcee9669.png)

**Comment by dotMorten** [comment] 2019-01-16 16:59
@OlteanuRadu Thank you. It looks like there needs to be a `if(Element != null)` check around these lines of code:
https://github.com/dotMorten/XamarinFormsControls/blob/master/AutoSuggestBox/dotMorten.Xamarin.Forms.AutoSuggestBox/AutoSuggestBoxRenderer.cs#L82-L91

**Comment by dotMorten** [comment] 2019-01-16 18:15
I can confirm the bug and issue has been fixed in v0.4.0

**Closed by dotMorten** 2019-01-16 18:15 UTC
Labels: F-AutoSuggestBox, bug
