### ISSUE TITLE
all SuggestionChosen methods fire when multiple AutoSuggestBox controls are present

### ISSUE THREAD

**Issue by IanLJohnson** [dotMorten/XamarinFormsControls#72] opened 2020-04-03 13:46 UTC
### Description
all SuggestionChosen methods fire when multiple AutoSuggestBox controls are present

### Steps to Reproduce

1. Create page with multiple AutoSuggestBoxes
2. Run app and select item in first Auto Suggest Box
3. SuggestionChosen method fires for first Auto Suggest Box and then fires for second

### Expected Behavior
Second SuggestionChosen method should not fire

### Actual Behavior
Second SuggestionChosen method fires too

### Basic Information

- Version with issue: 1.1.0
- Last known good version: 0.7.0
- IDE: VS 2019
- Platform Target Frameworks: Prism
  - iOS:  9.0
  - Android: 9.0 
  - UWP:  --
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- Affected Devices: tested on iOS

**Comment by dotMorten** [comment] 2020-04-03 14:11
Duplicate of #69. Should have an update out in a day or two

**Closed by dotMorten** 2020-04-03 14:11 UTC

**Comment by dotMorten** [comment] 2020-04-03 22:04
Fix published: https://www.nuget.org/packages/dotMorten.Xamarin.Forms.AutoSuggestBox/1.1.1

**Comment by FedericoJoseLucia** [comment] 2020-04-06 15:29
Works like a charm. Thanx!

**Comment by IanLJohnson** [comment] 2020-04-08 15:47
Really great your swift action in this matter, however if I look at the change set I notice that the only thing changes is the version number. Am I missing anything?

Kindest regards,
Ian

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dotMorten** [comment] 2020-04-08 15:57
@IanLJohnson There's a lot more than that:
https://github.com/dotMorten/XamarinFormsControls/compare/v1.1.0...v1.1.1

**Comment by IanLJohnson** [comment] 2020-04-08 16:00
Yes, I looked at all the change sets since my last visit and realize now that I was looking the first time at already work in progress.

Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
