### ISSUE TITLE
Problems with iOS (and sample code)

### ISSUE THREAD

**Issue by Schwabeneder** [dotMorten/XamarinFormsControls#17] opened 2018-09-20 10:14 UTC
Hello, 
I just tried the sample code from readme.md. I just copied the XAML code into a StackLayout of an existing XAML and copied the cs. code in the cs behind the XAML.
I got an error, because "Width" is a read only property, so i did remove the Width = "200" setting in the example XAML.
After that everything was fine on Android, but on iOS no suggestion box was shown at all.
I tried to set a WidthRequest and a HeightRequest, but that didn't do any good.
What could be the problem here?

**Comment by dotMorten** [comment] 2019-01-12 05:10
Thank you. I updated the sample to use `WidthRequest` (good catch).
I'm not sure why you're hitting that issue. Are you seeing the same issue with the sample app in this repo?
Could you share some sample code as a reproducer?

**Comment by dotMorten** [comment] 2019-01-14 20:34
Can't reproduce / not enough info. Closing

**Closed by dotMorten** 2019-01-14 20:34 UTC
Labels: More Info Needed
