### ISSUE TITLE
"Ambiguous match found" exception on UWP

### ISSUE THREAD

**Issue by wtheronjones** [dotMorten/XamarinFormsControls#22] opened 2018-12-12 23:50 UTC
### Description
Launching the AutoSuggestBoxSample.UWP app results in "ambiguous match found". 

The iOS and Android versions do not get this error.. the sample app for these platforms start as expected.

### Steps to Reproduce

1.  Download source, unzip
2.  Open in visual studio 2017 professional
3. Set "AutoSuggestBoxSample.UWP" as the Startup Project
4. Press F5 to start debugging.

### Expected Behavior
Sample app starts
### Actual Behavior
Sample app cannot start w/ stack trace:

System.Reflection.AmbiguousMatchException
  HResult=0x8000211D
  Message=Ambiguous match found.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name, BindingFlags bindingAttr)
   at System.Type.GetProperty(String name)
   at System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperty(Type type, String name) in E:\A\_work\2568\s\corefx\src\System.Runtime\src\System\Reflection\RuntimeReflectionExtensions.cs:line 74
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.TryGetProperty(Object element, String localName, Object& value, IXmlLineInfo lineInfo, HydrationContext context, Exception& exception, Object& targetProperty)

**Comment by dotMorten** [comment] 2019-01-12 05:06
@wtheronjones I'm not seeing this with the sample app. The stack trace doesn't seem to indicate anything from my code either. Can you see which property name it's faulting on?

**Comment by dotMorten** [comment] 2019-01-14 20:36
Can't reproduce. Closing for now

**Closed by dotMorten** 2019-01-14 20:36 UTC
Labels: More Info Needed
