### ISSUE TITLE
Text Size dont work

### ISSUE THREAD

**Issue by smithaliaga** [dotMorten/XamarinFormsControls#30] opened 2019-01-18 17:21 UTC
Text Size dont working

**Comment by dotMorten** [comment] 2019-01-18 17:49
Please provide mode information and use the issue template as I'm horrible at guessing

**Comment by dotMorten** [comment] 2019-01-18 23:37
Considering there are no TextSize or FontSize property on this class, I'm assuming this is a feature request? That means it's a duplicate of https://github.com/dotMorten/XamarinFormsControls/issues/2.

**Closed by dotMorten** 2019-01-18 23:37 UTC
Labels: F-AutoSuggestBox, More Info Needed, bug
