### ISSUE TITLE
Empty list

### ISSUE THREAD

**Issue by woemike** [dotMorten/XamarinFormsControls#70] opened 2020-03-30 00:14 UTC
### Description

This problem occurs only on iOS. If a finite list of suggestions (for example 5) is provided, the whole screen will be filled, after those suggestions, with empty rows.

### Steps to Reproduce

1. Use nugget on iOS and provide a custom item source.

### Basic Information

- Version with issue: 1.1.0
- Last known good version: -
- IDE: Visual Studio 2019, 16.5.1
- Platform Target Frameworks:
  - iOS: 13.4

### Screenshots
![Simulator Screen Shot - iPhone 11 Pro - 2020-03-30 at 03 04 07](https://user-images.githubusercontent.com/9967611/77864970-8c8ae480-7234-11ea-9980-cd6281aa374a.png)

**Comment by dotMorten** [comment] 2020-03-30 00:43
This is the behavior that iOS has for the selection list

**Comment by dotMorten** [comment] 2020-03-30 00:44
Duplicate of #48

**Closed by dotMorten** 2020-03-30 00:44 UTC

**Comment by irfanrana44772** [comment] 2020-08-31 18:55
hi doMorten,
if you are using ListView for opening the dropdown then set empty footer like footer="" in list Xaml.
I think your issue resolved with this query.
