### ISSUE TITLE
iOS renderer crashes when ItemsSource has values too early

### ISSUE THREAD

**Issue by kicsiede** [dotMorten/XamarinFormsControls#49] opened 2019-05-20 15:40 UTC
### Description
iOS renderer crashes (fails on applying layout constraints) if ItemsSource is set too early.
Probably because the view is not attached to a superview yet.

### Steps to Reproduce

try changing the constructor in the Simple example to this:

public Simple ()
{
            InitializeComponent();
            Initialize();
            SuggestBox1.ItemsSource = countries;
}

this is a showstopper for me because i initialize through bindings and set the BindingContext in the constructor.

### Expected Behavior

no crash :)

### Basic Information

- Version with issue: 0.7
- Last known good version: ?
- IDE: vs 2017
- Platform Target Frameworks:
  - iOS:  12.3

**Comment by majdaneq** [comment] 2019-09-10 09:53
Any workaround for this issue?

**Comment by mzaeemkhan** [comment] 2019-09-11 13:24
same issue here

**Comment by mzaeemkhan** [comment] 2019-09-11 14:27
Tested it on iOS. Working great. Thanks

**Comment by dotMorten** [comment] 2019-11-12 05:18
@kicsiede Sorry just getting around to looking into this now. I've tried adding the line of code you mentioned above, and that doesn't appear to cause any crash. Also tried setting the itemssource with a binding, or setting the itemssource specifically to null, and still nothing. Sample runs fine.
Could you share a more specific example and preferably a stack trace as well?

**Comment by AbdellahOusrhireDev** [comment] 2019-11-12 11:42
@dotMorten  Same problem occurs, would love to see this fixed

**Comment by dotMorten** [comment] 2019-11-12 14:28
@AbdellahOusrhireDev could you provide a sample app that reproduce this since I'm not seeing this.
A stack Trace would be helpful too

**Comment by dotMorten** [comment] 2020-01-27 05:19
Closing due to not being able to repro, and lacking information to trouble shoot. Feel free to provide a sample or at least a stack trace and reopen

**Comment by REDECODE** [comment] 2020-02-06 18:00
Same error for me on iOS 13.1.3.
The issue is caused if I assign the ItemsSource of the AutoSuggestBox in the constructor of the ContentPage with an ObservableCollection<string> with more than one value. The AutoSuggestBox  in my case is inside of a custom view, AutocompleteBoxed, see row 9 of the stack trace and AutocompleteBoxed is invisible:

Objective-C exception thrown.  Name: NSGenericException Reason: Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x280acbc80 "UITableView:0x10d1f5000.top"> and <NSLayoutYAxisAnchor:0x280acbbc0 "UITextField:0x10c3e9ca0.bottom"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.
Native stack trace:
	0   CoreFoundation                      0x000000018b1549a0 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 1227168
	1   libobjc.A.dylib                     0x000000018ae7d0a4 objc_exception_throw + 56
	2   Foundation                          0x000000018b42a40c 0DF2911E-80CB-3289-8A1E-ED0913D55A12 + 152588
	3   Test.iOS                         0x000000010625cbe8 wrapper_managed_to_native_ObjCRuntime_Messaging_void_objc_msgSend_bool_intptr_intptr_bool + 152
	4   Test.iOS                         0x00000001061b0060 UIKit_NSLayoutConstraint_set_Active_bool + 80
	5   Test.iOS                         0x0000000107568b48 dotMorten_Xamarin_Forms_Platform_iOS_iOSAutoSuggestBox_set_IsSuggestionListOpen_bool + 1688
	6   Test.iOS                         0x0000000107567f20 dotMorten_Xamarin_Forms_Platform_iOS_iOSAutoSuggestBox_SetItems_System_Collections_Generic_IEnumerable_1_object_System_Func_2_object_string_System_Func_2_object_string + 1280
	7   Test.iOS                         0x0000000107565560 dotMorten_Xamarin_Forms_Platform_iOS_AutoSuggestBoxRenderer_UpdateDisplayMemberPath + 672
	8   Test.iOS                         0x0000000107563610 dotMorten_Xamarin_Forms_Platform_iOS_AutoSuggestBoxRenderer_OnElementChanged_Xamarin_Forms_Platform_iOS_ElementChangedEventArgs_1_dotMorten_Xamarin_Forms_AutoSuggestBox + 2320
	9   Test.iOS                         0x00000001050f4dc8 Test_iOS_Custom_AutocompleteBoxedRenderer_OnElementChanged_Xamarin_Forms_Platform_iOS_ElementChangedEventArgs_1_dotMorten_Xamarin_Forms_AutoSuggestBox + 136
	10  Test.iOS                         ...
	

The workaround suggested (assign the ItemsSource property on Focused event) worked for me

**Comment by dotMorten** [comment] 2020-02-06 18:01
@REDECODE Any chance you could supply a repro? I haven't been able to reproduce this issue

**Comment by REDECODE** [comment] 2020-02-06 18:06
I try to reproduce it but I need time to create a new project with only that component.. then I'll send it to you

**Comment by REDECODE** [comment] 2020-02-06 18:50
You can download a sample from this link on Drive:
https://drive.google.com/file/d/1RDfXfQP6lN6ZNTIrlq70A04vbA98oWVR/view?usp=sharing

**Comment by dotMorten** [comment] 2020-02-07 01:24
Thank you! Much appreciated! I can repro with this. Looks like it's a constraint update issue. I'll try and get this addressed in the next few days

**Comment by dotMorten** [comment] 2020-02-07 04:20
Should be fixed now. Let me know if this works for you too. Thank you so much for the reproducer! That made it so much simpler to fix.

**Closed** 2020-02-07 04:20 UTC
Labels: F-AutoSuggestBox, Platform Specific: iOS, bug

**Comment by REDECODE** [comment] 2020-02-07 09:39
It works! Many thanks to you and your component, it's really usefull.
Have a good day :)

**Comment by dotMorten** [comment] 2020-02-07 14:36
And thank you. A repro makes all the difference for me!
