### ISSUE TITLE
Bound Text property not updating ViewModel MVVM

### ISSUE THREAD

**Issue by josegomez** [dotMorten/XamarinFormsControls#10] opened 2018-07-16 17:13 UTC
When you bind the Text property to an MVVM it is expected that changes to the Text Property will notify the bound ViewModel.
This does not appear to be the case.

**Comment by dotMorten** [comment] 2018-07-26 03:21
Could you provide a reproducer sample?

**Comment by MarcosCobena** [comment] 2018-08-22 13:05
@josegomez sorry but looking at master it's just the opposite: OneWay, updates from the VM update the View. You can change it however.

https://github.com/dotMorten/XamarinFormsControls/blob/master/AutoSuggestBox/dotMorten.Xamarin.Forms.AutoSuggestBox/AutoSuggestBox.cs#L89

**Comment by il-frans** [comment] 2018-10-10 16:52
I agree with @MarcosCobena, cloned the code and changed to TwoWay, problem solved. this bug can be easily closed by implementing the fix

**Comment by RaashVision** [comment] 2018-12-18 15:59
Does this bug been fix and the newest nuget package contain the fixed?

**Comment by dotMorten** [comment] 2019-01-11 21:48
Can't you just set the `BindingMode=TwoWay` ? That worked for me.
`OneWay` also matches the behavior you see with UWP's `AutoSuggestBox` which this control is intended to mimic. Therefore I'm closing this `As Designed`

**Closed by dotMorten** 2019-01-11 21:48 UTC
Labels: wontfix
